#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_SETTINGS_MODULE=config.settings.production.base

python /{{ cookiecutter.project_slug }}/manage.py migrate
python /{{ cookiecutter.project_slug }}/manage.py init_roles
python /{{ cookiecutter.project_slug }}/manage.py init_schedule

exec celery -A config.celery_app beat -l INFO
